version: 2
updates:
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '00:00'
      timezone: 'Europe/Prague'
    commit-message:
      prefix: 'chore'
    labels:
      - 'Dependencies | Queued'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '00:00'
      timezone: 'Europe/Prague'
    commit-message:
      prefix: 'chore'
    labels:
      - 'Dependencies | Queued'
